In [44]:
import pandas as pd
import numpy as np

In [478]:
TEST = 'ping_test/ping_icmp_3.csv'
TEST_OUPUT = 'output/ping/ping_icmp_3_processed.csv'

# PING_TEST = 'ping_test/ping_tcp_1.csv'
# PING_TEST_OUTPUT = 'output/ping/ping_tcp_1_processed.csv'
# BROWSER_TEST = 'Browsing.csv'
# BROWSER_TEST_OUTPUT = 'output/browser_summary.csv'

In [479]:
# df = pd.read_csv('ping_test/ping_tcp_3.csv')
df = pd.read_csv(TEST)
# df.rename(columns={'Time': 'Time1'}, inplace=True)

In [480]:
# Get time span before filtering
time_span_raw = df['Time'].max() - df['Time'].min()
print(f"Time span (before processing): {time_span_raw} seconds")

Time span (before processing): 301.6803273 seconds

In [481]:
df.head()

,No.,Time,Source,Destination,Protocol,Length,Info
0,5,0.460148,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=887/30467,..."
1,6,0.491987,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=887/30467,..."
2,12,1.480001,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=888/30723,..."
3,13,1.516593,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=888/30723,..."
4,17,2.499568,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=889/30979,..."

In [482]:
df['Protocol'].value_counts()

Protocol
ICMP    513
Name: count, dtype: int64

In [483]:
# Use this if you want to filter by protocol and port (e.g., HTTP/HTTPS)

# mask_protocol = df['Protocol'].isin(['TCP', 'UDP'])  # Adjust protocol names as needed [e.g., 'TCP', 'UDP']
# mask_port = df['Info'].str.contains(r'\b80\b|\b443\b', na=False)
# df_filtered = df[mask_protocol | mask_port]

df_filtered = df

In [484]:
df_filtered

,No.,Time,Source,Destination,Protocol,Length,Info
0,5,0.460148,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=887/30467,..."
1,6,0.491987,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=887/30467,..."
2,12,1.480001,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=888/30723,..."
3,13,1.516593,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=888/30723,..."
4,17,2.499568,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=889/30979,..."
...,...,...,...,...,...,...,...
508,4776,300.018416,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=1141/29956..."
509,4781,300.998401,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=1142/30212..."
510,4782,301.032246,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=1142/30212..."
511,4794,302.105890,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=1143/30468..."
512,4795,302.140475,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=1143/30468..."

In [485]:
df_filtered.value_counts('Protocol')

Protocol
ICMP    513
Name: count, dtype: int64

In [486]:
df_filtered.head()

,No.,Time,Source,Destination,Protocol,Length,Info
0,5,0.460148,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=887/30467,..."
1,6,0.491987,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=887/30467,..."
2,12,1.480001,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=888/30723,..."
3,13,1.516593,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=888/30723,..."
4,17,2.499568,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=889/30979,..."

In [487]:
df_filtered['Time1'] = df['Time']
df_filtered['Time2'] = df_filtered['Time1'].shift(-1)

df_filtered['Delay'] = df_filtered['Time2'] - df_filtered['Time1']
df_filtered['Delay1'] = df_filtered['Delay'] - df_filtered['Delay'].shift(-1)

df_filtered['Delay2'] = df_filtered['Delay1'].shift(-1)
df_filtered['Jitter'] = np.abs(df_filtered['Delay2'] - df_filtered['Delay1'])

df_filtered.head()

,No.,Time,Source,Destination,Protocol,Length,Info,Time1,Time2,Delay,Delay1,Delay2,Jitter
0,5,0.460148,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=887/30467,...",0.460148,0.491987,0.031839,-0.956175,0.951423,1.907599
1,6,0.491987,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=887/30467,...",0.491987,1.480001,0.988015,0.951423,-0.946383,1.897806
2,12,1.480001,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=888/30723,...",1.480001,1.516593,0.036592,-0.946383,0.944424,1.890807
3,13,1.516593,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=888/30723,...",1.516593,2.499568,0.982975,0.944424,-0.948043,1.892467
4,17,2.499568,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=889/30979,...",2.499568,2.538118,0.038550,-0.948043,0.954004,1.902047

In [488]:
request_mask = df_filtered['Info'].str.contains(r'^Echo \(ping\) request', case=False)
reply_mask = df_filtered['Info'].str.contains(r'^Echo \(ping\) reply', case=False)

request_df_filtered = df_filtered[request_mask]
reply_df_filtered = df_filtered[reply_mask]

In [489]:
# Reorder columns - No first, then Time1, Time2, etc
cols_order = ['No.', 'Time', 'Time1', 'Time2', 'Delay', 'Delay1', 'Delay2', 'Jitter']
other_cols = [col for col in df_filtered.columns if col not in cols_order]
df_filtered = df_filtered[cols_order + other_cols]
df_filtered.head()

,No.,Time,Time1,Time2,Delay,Delay1,Delay2,Jitter,Source,Destination,Protocol,Length,Info
0,5,0.460148,0.460148,0.491987,0.031839,-0.956175,0.951423,1.907599,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=887/30467,..."
1,6,0.491987,0.491987,1.480001,0.988015,0.951423,-0.946383,1.897806,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=887/30467,..."
2,12,1.480001,1.480001,1.516593,0.036592,-0.946383,0.944424,1.890807,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=888/30723,..."
3,13,1.516593,1.516593,2.499568,0.982975,0.944424,-0.948043,1.892467,216.239.38.120,192.168.2.144,ICMP,74,"Echo (ping) reply id=0x0001, seq=888/30723,..."
4,17,2.499568,2.499568,2.538118,0.038550,-0.948043,0.954004,1.902047,192.168.2.144,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=889/30979,..."

In [490]:
# df_filtered.to_csv('output/ping_tcp_3_processed.csv', index=False)
df_filtered.to_csv(TEST_OUPUT, index=False)

In [491]:
raise StopIteration("Stop")

StopIteration: Stop

In [ ]:
test_1  = pd.read_csv('output/ping/ping_icmp_1_processed.csv')
test_2  = pd.read_csv('output/ping/ping_icmp_2_processed.csv')
test_3  = pd.read_csv('output/ping/ping_icmp_3_processed.csv')

In [ ]:
np.sum(test_1['Length'])

np.int64(44474)

In [ ]:
# Load raw data to get raw time spans
raw_test_1 = pd.read_csv('ping_test/ping_icmp_1.csv')
raw_test_2 = pd.read_csv('ping_test/ping_icmp_2.csv')
raw_test_3 = pd.read_csv('ping_test/ping_icmp_3.csv')


# Calculate raw time spans before any filtering
raw_time_span_1 = raw_test_1['Time'].max() - raw_test_1['Time'].min()
raw_time_span_2 = raw_test_2['Time'].max() - raw_test_2['Time'].min()
raw_time_span_3 = raw_test_3['Time'].max() - raw_test_3['Time'].min()

print(f"Raw Time Span Test 1: {raw_time_span_1:.6f} seconds")
print(f"Raw Time Span Test 2: {raw_time_span_2:.6f} seconds")
print(f"Raw Time Span Test 3: {raw_time_span_3:.6f} seconds")

Raw Time Span Test 1: 307.918150 seconds
Raw Time Span Test 2: 310.722727 seconds
Raw Time Span Test 3: 301.680327 seconds

In [ ]:
len(raw_test_1)

601

In [ ]:
raw_test_1.head()

,No.,Time,Source,Destination,Protocol,Length,Info,Unnamed: 7,Unnamed: 8
0,7,2.536215,192.168.2.137,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=347/23297,...",NaN,COUN
1,8,2.572018,216.239.38.120,192.168.2.137,ICMP,74,"Echo (ping) reply id=0x0001, seq=347/23297,...",NaN,NaN
2,9,3.546034,192.168.2.137,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=348/23553,...",NaN,NaN
3,10,3.590494,216.239.38.120,192.168.2.137,ICMP,74,"Echo (ping) reply id=0x0001, seq=348/23553,...",NaN,NaN
4,11,4.559463,192.168.2.137,216.239.38.120,ICMP,74,"Echo (ping) request id=0x0001, seq=349/23809,...",NaN,NaN

In [ ]:
raw_test_1['Protocol'].value_counts()

Protocol
ICMP    601
Name: count, dtype: int64

In [ ]:
test_1['Protocol'].value_counts()

Protocol
ICMP    601
Name: count, dtype: int64

In [ ]:
throughput_1 = (np.sum(test_1['Length'] * 8) / raw_time_span_1) / 1000
throughput_2 = (np.sum(test_2['Length'] * 8) / raw_time_span_2) / 1000
throughput_3 = (np.sum(test_3['Length'] * 8) / raw_time_span_3) / 1000

print(f"Throughput Test 1: {throughput_1:.6f} kbps")
print(f"Throughput Test 2: {throughput_2:.6f} kbps")
print(f"Throughput Test 3: {throughput_3:.6f} kbps")

Throughput Test 1: 1.155476 kbps
Throughput Test 2: 0.712558 kbps
Throughput Test 3: 1.006681 kbps

In [ ]:
packet_loss = 0

In [ ]:
total_delay_test_1 = np.sum(test_1['Delay'].dropna())
total_delay_test_2 = np.sum(test_2['Delay'].dropna())
total_delay_test_3 = np.sum(test_3['Delay'].dropna())

In [ ]:
print(total_delay_test_1)

307.9181495

In [ ]:

delay_avg_1 = total_delay_test_1 / len(raw_test_1)
delay_avg_2 = total_delay_test_2 / len(raw_test_2)
delay_avg_3 = total_delay_test_3 / len(raw_test_3)

In [ ]:
print(delay_avg_1)

0.5123430108153079

In [ ]:
jitter_1 = np.average(test_1['Jitter'].dropna()) * 1000
jitter_2 = np.average(test_2['Jitter'].dropna()) * 1000
jitter_3 = np.average(test_3['Jitter'].dropna()) * 1000

In [ ]:
total_jitter_test_1 = np.sum(test_1['Jitter'].dropna())
total_jitter_test_2 = np.sum(test_2['Jitter'].dropna())
total_jitter_test_3 = np.sum(test_3['Jitter'].dropna())

In [ ]:
average_jitter_test_1 = total_jitter_test_1 / len(raw_test_1)
average_jitter_test_2 = total_jitter_test_2 / len(raw_test_2)
average_jitter_test_3 = total_jitter_test_3 / len(raw_test_3)

In [ ]:
output_df = pd.DataFrame({
    'Test': ['Test 1', 'Test 2', 'Test 3'],
    'Raw Time Span (s)': [raw_time_span_1, raw_time_span_2, raw_time_span_3],
    'Throughput (kbps)': [throughput_1, throughput_2, throughput_3],
    'Packet Loss (%)': [packet_loss, packet_loss, packet_loss],
    'Total Delay (s)': [total_delay_test_1, total_delay_test_2, total_delay_test_3],
    'Avg Delay (s)': [delay_avg_1, delay_avg_2, delay_avg_3],
    'Total Jitter (s)': [total_jitter_test_1, total_jitter_test_2, total_jitter_test_3],
    'Avg Jitter (s)': [average_jitter_test_1, average_jitter_test_2, average_jitter_test_3],
    'Jitter (ms)': [jitter_1, jitter_2, jitter_3]
})

output_df.to_csv('output/summary.csv', index=False)
print(output_df)

     Test  Raw Time Span (s)  Throughput (kbps)  Packet Loss (%)  \
0  Test 1         307.918150           1.155476                0
1  Test 2         310.722727           0.712558                0
2  Test 3         301.680327           1.006681                0

   Total Delay (s)  Average Delay (s)  Total Jitter (s)  Avg Jitter (s)  \
0       307.918150           0.512343       1137.544045        1.892752
1       310.722727           0.830809       1152.989174        3.082859
2       301.680327           0.588071       1109.193510        2.162171

   Jitter (ms)
0  1902.247567
1  3107.787532
2  2174.889235